version: "3"
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./img:/app/img
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - webnet
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - api
    networks:
      - webnet
networks:
  webnet:
