version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - '3000:3000'
      - '3443:3443'
    environment:
      - HTTP_PORT=3000
      - HTTPS_PORT=3443
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - api
